#!/bin/sh

function betterdoc {
  cd "$HOME/code/betterdoc"

  tmux start-server
  tmux new-session -d -s betterdoc -n editor
  tmux new-window -t betterdoc:2 -n git
  tmux new-window -t betterdoc:3 -n console
  tmux new-window -t betterdoc:4 -n server

  tmux send-keys -t betterdoc:1 "vim" C-m
  tmux send-keys -t betterdoc:2 "gg" C-m
  tmux send-keys -t betterdoc:3 "spring rails c" C-m
  tmux send-keys -t betterdoc:4 "foreman start" C-m

  tmux select-window -t betterdoc:1
  tmux split-window -h
  tmux select-pane -t 2
  tmux send-keys "RPROMPT=" C-m
  tmux resize-pane -t 2 -R 60
  tmux select-pane -t 1

  tmux attach-session -t betterdoc
}

function spotbe {
  cd "$HOME/code/spotbe"

  tmux start-server
  tmux new-session -d -s spotbe -n editor
  tmux new-window -t spotbe:2 -n git
  tmux new-window -t spotbe:3 -n console
  tmux new-window -t spotbe:4 -n server

  tmux send-keys -t spotbe:1 "vim" C-m
  tmux send-keys -t spotbe:2 "gg" C-m
  tmux send-keys -t spotbe:3 "spring rails c" C-m
  tmux send-keys -t spotbe:4 "foreman start -f Procfile.dev" C-m

  tmux select-window -t spotbe:1
  tmux split-window -h
  tmux select-pane -t 2
  tmux send-keys "RPROMPT=" C-m
  tmux resize-pane -t 2 -R 60
  tmux select-pane -t 1

  tmux attach-session -t spotbe
}

function doutore {
  cd "$HOME/code/doctorhouse"

  tmux start-server
  tmux new-session -d -s doutore -n editor
  tmux new-window -t doutore:2 -n git
  tmux new-window -t doutore:3 -n console
  tmux new-window -t doutore:4 -n server

  tmux send-keys -t doutore:1 "vim" C-m
  tmux send-keys -t doutore:2 "gg" C-m
  tmux send-keys -t doutore:3 "rails c" C-m
  tmux send-keys -t doutore:4 "rails s -p 3003 -b 127.0.0.1" C-m

  tmux select-window -t doutore:1
  tmux split-window -h
  tmux select-pane -t 2
  tmux send-keys "RPROMPT=" C-m
  tmux resize-pane -t 2 -R 60
  tmux select-pane -t 1

  tmux attach-session -t doutore
}

function mct_funder {
  cd "$HOME/code/mct_funder"

  tmux start-server
  tmux new-session -d -s mct_funder -n editor
  tmux new-window -t mct_funder:2 -n git
  tmux new-window -t mct_funder:3 -n console
  tmux new-window -t mct_funder:4 -n server

  tmux send-keys -t mct_funder:1 "vim" C-m
  tmux send-keys -t mct_funder:2 "gg" C-m
  tmux send-keys -t mct_funder:3 "rails c" C-m
  tmux send-keys -t mct_funder:4 "rails s -p 3004 -b 127.0.0.1" C-m

  tmux select-window -t mct_funder:1
  tmux split-window -h
  tmux select-pane -t 2
  tmux send-keys "RPROMPT=" C-m
  tmux resize-pane -t 2 -R 60
  tmux select-pane -t 1

  tmux attach-session -t mct_funder
}

